-- 003_images.sql — pasted images, moved out of the removed Vercel KV store.
--
-- An image is permanent: a note references `/api/img?id=…` forever. That rules out
-- the Redis that now holds tiny links, which is in-memory and runs an evicting
-- maxmemory policy — an evicted image is a hole in someone's note. Postgres is
-- durable, disk-priced and already backed up.
--
-- Rows belong to a user. An anonymous upload endpoint writing into the database that
-- holds everyone's notes would let anyone fill its disk; ownership gives the quota in
-- api/img.js something to count and lets ON DELETE CASCADE clean up.
--
-- Nothing is migrated in: the KV store is gone, so its images are gone with it and
-- their links 404.

BEGIN;

CREATE TABLE images (
  -- Generated by api/ids.js. The CHECK duplicates img.js's regex on purpose: a row
  -- that bypassed the handler still cannot hold an id the GET path would refuse.
  id         text        PRIMARY KEY CHECK (id ~ '^[a-z0-9]{8,16}$'),
  user_id    uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- The same allowlist as notes-store.js UPLOAD_TYPES; GET sends it as Content-Type.
  mime       text        NOT NULL CHECK (mime IN ('image/jpeg', 'image/png', 'image/webp', 'image/gif')),
  bytes      bytea       NOT NULL,
  -- Generated, like notes.block_count in 001, so the quota sums a value no client
  -- can supply.
  byte_size  integer     GENERATED ALWAYS AS (octet_length(bytes)) STORED,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- The quota check sums one user's images on every upload.
CREATE INDEX images_user_idx ON images (user_id);

COMMIT;
